Repository piccolo-orm/piccolo_admin, pull requests merged in 2022-08, with the labels that each got.

#189 File upload support
  .github/workflows/tests.yaml
  .gitignore
  admin_ui/package-lock.json
  admin_ui/package.json
  admin_ui/src/components/ArrayWidget.vue
  admin_ui/src/components/InputField.vue
  admin_ui/src/components/LoadingOverlay.vue
  admin_ui/src/components/MediaViewer.vue
  admin_ui/src/components/OperatorField.vue
  admin_ui/src/fontawesome.ts
  admin_ui/src/interfaces.ts
  admin_ui/src/main.less
  admin_ui/src/views/RowListing.vue
  admin_ui/tsconfig.json
  docs/source/api_reference/index.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/media_storage/images/media_upload.png
  docs/source/media_storage/images/sample_ui/media_viewer_audio.png
  docs/source/media_storage/images/sample_ui/media_viewer_image.png
  docs/source/media_storage/images/sample_ui/media_viewer_pdf.png
  docs/source/media_storage/images/sample_ui/media_viewer_video.png
  docs/source/media_storage/index.rst
  extra/piccolo_admin
  piccolo_admin/endpoints.py
  piccolo_admin/example.py
  piccolo_admin/example_media/.gitkeep
  piccolo_admin/media/__init__.py
  piccolo_admin/media/base.py
  piccolo_admin/media/local.py
  piccolo_admin/media/s3.py
  piccolo_admin/static/.gitkeep
  requirements/dev-requirements.txt
  requirements/extra/faker.txt
  requirements/extra/s3.txt
  requirements/test-requirements.txt
  setup.py
  tests/files/bulb.jpg
  tests/media/test_base.py
  tests/media/test_files/bulb.jpg
  tests/media/test_local.py
  tests/media/test_s3.py
  tests/test_endpoints.py
Labels: enhancement

#195 add list of standout features to README
  README.md
Labels: documentation

#198 media upload endpoints obey read_only option
  piccolo_admin/endpoints.py
  tests/test_endpoints.py
Labels: enhancement

#208 fix custom forms
  admin_ui/src/components/InputField.vue
  admin_ui/src/components/RowFormSelect.vue
Labels: bug
